Repository Option7-OctoPuss/MeetYourTesterGame, pull requests merged in 2024-03, with the labels that each got.

#137 feat: Add aftermath color var to terminal output, changed persona col…
  MeetYourTesterProject/ui/main_screen/terminal/handle_terminal.gd
Labels: enhancement

#138 fix: deleted unnecessary metadata
  .github/ISSUE_TEMPLATE/custom-user-story-template.md
Labels: documentation

#144 102 implement exit game on main menu scene
  MeetYourTesterProject/scripts/stores/globals.gd
  MeetYourTesterProject/ui/menus/exit_menu_scene.gd
  MeetYourTesterProject/ui/menus/handle_main_menu.gd
Labels: RED
